#!/bin/python

with open("valid.cimg", "wb") as f:
    f.write(b"cIMG")                    
    f.write((1).to_bytes(4, "little"))  
    f.write((79).to_bytes(2, "little")) 
    f.write((24).to_bytes(4, "little"))

    f.write(b"\x20" * (79 * 24))
